# Database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=mysqlpw
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

springdoc.api-docs.path=/cliente/api-docs
springdoc.swagger-ui.path=/cliente.html


##CLOUD-SQL-CONFIGURATIONS
spring.cloud.gcp.sql.database-name=cajalosheroesmysql
spring.cloud.gcp.sql.instance-connection-name=app-caja-los-heroes-cliente:us-central1:cajalosheroesmysqlgcp
# So app starts despite "table already exists" errors.
#spring.datasource.continue-on-error=true
# Enforces database initialization
#spring.datasource.initialization-mode=always
spring.cloud.gcp.project-id=app-caja-los-heroes-cliente
#spring.cloud.gcp.spanner.instance-id=dark-runway-367507:us-central1:mysqlgcp
#spring.cloud.gcp.credentials.location=file:/src/main/resources/key.json
